### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by jchadwick** [jediwhale/fitsharp#119]
I searched FitSharp in the NuGet repository and nothing came up.  It'd be great to have a package in there.

I'm putting one together and posting it. I'll happily take it down if/when you'd like to take over.

**Comment by Brehme** [comment]
Do you plan to upgrade the nuget-package to the newest fitsharp-version?

**Comment by jchadwick** [comment]
Yes, I can upgrade it but, frankly, I was hoping someone else would take it over... :)

**Comment by jediwhale** [comment]
If you make me an owner I'll update it.

**Comment by jediwhale** [comment]
updated
