### ISSUE TITLE
RowFixture not being treated like a RowFixture (Method setname1 not found in namespace.assembly)

### ISSUE THREAD

**Issue by c0achmcguirk** [jediwhale/fitsharp#128]
I'm having a hard time getting fitSharp to recognize the RowFixture I've created.

Here's my RowFixture, I'm basically using the `SampleRowFixture` included in the project:

 ```csharp
using fit;
using System;

namespace SomeNamespace
{
    public class SampleRowFixture : RowFixture
    {
        public override object[] Query()
        {
            return new TwoNames[] { new TwoNames("too short", "<stuff>"), new TwoNames("too", "too") };
        }

        public override Type GetTargetClass()
        {
            return typeof(TwoNames);
        }

        public class TwoNames
        {
            public string name1;
            public string name2;
            public TwoNames(string theFirst, string theSecond)
            {
                name1 = theFirst;
                name2 = theSecond;
            }
        }
    }
}
```

My fit test looks like this:

    !|SomeNamespace.SampleRowFixture|
    |name1|name2|
    |too short||
    |too|too|
    |extra|extra|

I get an output that looks like this:

![rowfailureerror](https://cloud.githubusercontent.com/assets/1066899/6034168/22ab01fa-abe5-11e4-89bc-6751a4c953c8.png)

It's trying to invoke `setname1` on the test fixture rather than on the TargetClass `TwoNames`. I'm able to get a ColumnFixture to work, no problem, but the RowFixture doesn't seem to behave with what I've tried so far.

In stepping through code, it looks like my problem is in `MemberQuery.cs` line 48 where it calls

    var member = finder(new TypedValue(target), this);

It can't find the `TwoNames` class. Here's a screenshot of what I mean...`member.HasValue` is false because it can't find the `TwoNames` class.

![rowfixtureerror2](https://cloud.githubusercontent.com/assets/1066899/6034302/cb1f0a1a-abe6-11e4-8a64-ed2118e8a5b4.png)

What am I missing?

**Comment by jediwhale** [comment]
You are running with test system slim - you need test system fit

!define TEST_SYSTEM {fit}


On 2015-02-03 19:54, Paul M Oliver wrote:
>
> I'm having a hard time getting fitSharp to recognize the RowFixture 
> I've created.
>
> Here's my RowFixture, I'm basically using the |SampleRowFixture| 
> included in the project:
>
> |using fit;
> using System;
>
> namespace SomeNamespace
> {
>      public class SampleRowFixture : RowFixture
>      {
>          public override object[] Query()
>          {
>              return new TwoNames[] { new TwoNames("too short", "<stuff>"), new TwoNames("too", "too") };
>          }
>
>          public override Type GetTargetClass()
>          {
>              return typeof(TwoNames);
>          }
>
>          public class TwoNames
>          {
>              public string name1;
>              public string name2;
>              public TwoNames(string theFirst, string theSecond)
>              {
>                  name1 = theFirst;
>                  name2 = theSecond;
>              }
>          }
>      }
> }
> |
>
> My fit test looks like this:
>
> |!|SomeNamespace.SampleRowFixture|
> |name1|name2|
> |too short||
> |too|too|
> |extra|extra|
> |
>
> I get an output that looks like this:
>
> rowfailureerror 
> <https://cloud.githubusercontent.com/assets/1066899/6034168/22ab01fa-abe5-11e4-89bc-6751a4c953c8.png>
>
> It's trying to invoke |setname1| on the test fixture rather than on 
> the TargetClass |TwoNames|. I'm able to get a ColumnFixture to work, 
> no problem, but the RowFixture doesn't seem to behave with what I've 
> tried so far.
>
> In stepping through code, it looks like my problem is in 
> |MemberQuery.cs| line 48 where it calls
>
> |var member = finder(new TypedValue(target), this);
> |
>
> It can't find the |TwoNames| class. Here's a screenshot of what I 
> mean...|member.HasValue| is false because it can't find the |TwoNames| 
> class.
>
> rowfixtureerror2 
> <https://cloud.githubusercontent.com/assets/1066899/6034302/cb1f0a1a-abe6-11e4-8a64-ed2118e8a5b4.png>
>
> What am I missing?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jediwhale/fitsharp/issues/128>.
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>
Syterra Software Inc. <http://www.syterra.com>

**Comment by c0achmcguirk** [comment]
Incredible, that solved all my problems. Thanks for the help. I changed my test **from this**:

```
!define TEST_SYSTEM {fit}
!path C:\Projects\UsefulService\FitnesseTestFixtures\bin\Debug\MyCompany.UsefulService.FitnesseTestFixtures.dll
!define COMMAND_PATTERN {%m -r fitSharp.Slim.Service.Runner %p}
!define TEST_RUNNER {c:\FitNesse\fitSharp\Runner.exe}
```

**to this**
```
!path C:\Projects\UsefulService\FitnesseTestFixtures\bin\Debug\MyCompany.UsefulService.FitnesseTestFixtures.dll
!define COMMAND_PATTERN {%m -r fitnesse.fitserver.FitServer -a C:\Projects\UsefulService\FitnesseTestFixtures\App.config %p}
!define TEST_RUNNER {c:\FitNesse\fitSharp\Runner.exe}
```

And now everything is working swimmingly.
