### ISSUE TITLE
Query Tables do not fully support constructors which have more than one argument, when one argument is a Dictionary type

### ISSUE THREAD

**Issue by InspiredIdealist** [jediwhale/fitsharp#129]

**Comment by InspiredIdealist** [comment]
Example:

query: Query Fixture | !{hash:map}|string|
------------ | -------------|----------------|-------|
column1 | column2
row1|row1|

**Comment by jediwhale** [comment]
This worked:
|query:sampleclass|!{name:bob}|extra|
|key|value|
|name|bob|

with code:

    public class SampleClass {
         public SampleClass(Dictionary<string, string> dictionary, string extra) {
            this.dictionary = dictionary; 
        }
        public List<object> query() {
            return dictionary.Keys.Select(key => new List<object> {
                new List<object> {"key", key}, new List<object> {"value", dictionary[key]},
            }).Cast<object>().ToList();
        }
        readonly Dictionary<string, string> dictionary;
    }

**Comment by InspiredIdealist** [comment]
Sorry, I gave a bad example. The one case where this does not work (please try this one):

query: Query Fixture | !{hash:map}|!{hash:map}|
------------ | -------------|--------|
column1 | column2
row1|row1|

**Comment by jediwhale** [comment]
This works:
|query:sampleclass|!{name:bob}|!{name:bob}|
|key|value|
|name|bob|

 with
` 
       public SampleClass(Dictionary<string, string> dictionary, Dictionary<string, string> extra) {
            this.dictionary = dictionary; 
        }
`

Please post your code and the error you're seeing.
