### ISSUE TITLE
SqlServer Time-Type

### ISSUE THREAD

**Issue by OB4** [jediwhale/fitsharp#130]
Hello @jediwhale, I found an error in the code. In line 217 of the function "protected static Type GetDotNetType(String dataType)" of "dbfitSqlServer.SqlServerEnvironment.cs " the correct code for the Time-Type is:
if (Array.IndexOf(TimeTypes, dataType) >= 0) return typeof(TimeSpan);
The return-type have to be a TimeSpan!

**Comment by fijiaaron** [comment]
I can't speak to this, but it would really help if you could sent it as a pull request -- even better if you can include a unit test demonstrating the issue that passes when it is fixed.

**Comment by jediwhale** [comment]
pull request merged
