### ISSUE TITLE
Feature Request: Please kindly port LookupTable from FitLibraryWeb to fitSharp.

### ISSUE THREAD

**Issue by rahuldixit** [jediwhale/fitsharp#133]
Hi,

In FitLibraryWeb there is a feature called lookup table. It allows you to set a symbol value to be anything in a lookup table, based a set of input conditions. I would like to request that this be ported to fitSharp. It is an incredibly useful feature, saving much time on test case development.

Below is snapshot of usage:
Below, User and Page are symbols, Action is the result symbol. You call the appropriate action based on the user and page i.e. the output value is saved to the symbol based on input values.

|set|User||User A|
|set|Page||Page 2|

!|LookupTable|
|User    |Page  |Action?        |
|User A|Page 1|verify page 1|
|User A|Page 2|verify page 2|
|User B|Page 3|verify page 3|

|<<Action| # calls the defined procedure 'verify page 2'

Let me know if you will be looking into this and implementing it. Many Thanks.

I had tried doing this myself but got stuck when I tried calling the method |<<Action|, which resulted in a null exception reference. 

I call below code which gives error:
Processor.ExecuteWithThrow(this, rest.Parts, null, rest.Parts);

I can give you my code if you like, let me know: rahul.dixit.zero@gmail.com

Kind Regards,
Rahul Dixit

**Comment by jediwhale** [comment]
I'll look at it this weekend...
On 2015-05-10 20:57, rahuldixit wrote:
>
> Hi,
>
> In FitLibraryWeb there is a feature called lookup table. It allows you 
> to set a symbol value to be anything in a lookup table, based a set of 
> input conditions. I would like to request that this be ported to 
> fitSharp. It is an incredibly useful feature, saving much time on test 
> case development.
>
> Below is snapshot of usage:
> Below, User and Page are symbols, Action is the result symbol. You 
> call the appropriate action based on the user and page i.e. the output 
> value is saved to the symbol based on input values.
>
> |set|User||User A|
> |set|Page||Page 2|
>
> !|LookupTable|
> |User |Page |Action? |
> |User A|Page 1|verify page 1|
> |User A|Page 2|verify page 2|
> |User B|Page 3|verify page 3|
>
> |<<Action| # calls the defined procedure 'verify page 2'
>
> Let me know if you will be looking into this and implementing it. Many 
> Thanks.
>
> I had tried doing this myself but got stuck when I tried calling the 
> method |<<Action|, which resulted in a null exception reference.
>
> I call below code which gives error:
> Processor.ExecuteWithThrow(this, rest.Parts, null, rest.Parts);
>
> I can give you my code if you like, let me know: 
> rahul.dixit.zero@gmail.com <mailto:rahul.dixit.zero@gmail.com>
>
> Kind Regards,
> Rahul Dixit
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jediwhale/fitsharp/issues/133>.
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>
Syterra Software Inc. <http://www.syterra.com>

**Comment by rahuldixit** [comment]
Hi Mike,

I just want to follow up on this and check the status of this feature request. Did you get a chance to look at it?

Many Thanks,
Rahul Dixit

**Comment by jediwhale** [comment]
It is in progress.

On 2015-06-09 15:02, rahuldixit wrote:
>
> Hi Mike,
>
> I just want to follow up on this and check the status of this feature 
> request. Did you get a chance to look at it?
>
> Many Thanks,
> Rahul Dixit
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jediwhale/fitsharp/issues/133#issuecomment-110503081>.
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>
Syterra Software Inc. <http://www.syterra.com>

**Comment by rahuldixit** [comment]
Hi Mike,

I just want to follow up on this and check the status of this feature request. When do you expect this to be ready?

Many Thanks,
Rahul Dixit

**Comment by jediwhale** [comment]
Just returned from vacation!  Should be done in about 2 weeks.

On 2015-08-25 22:14, rahuldixit wrote:
>
> Hi Mike,
>
> I just want to follow up on this and check the status of this feature 
> request. When do you expect this to be ready?
>
> Many Thanks,
> Rahul Dixit
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jediwhale/fitsharp/issues/133#issuecomment-134824150>.
>

-- 
Cheers,
Mike Stockdale

/fit/Sharp <http://fitsharp.github.com>
Syterra Software Inc. <http://www.syterra.com>

**Comment by jediwhale** [comment]
new fixture: MatchValue
