### ISSUE TITLE
No suite test summary generated

### ISSUE THREAD

**Issue by ingek** [jediwhale/fitsharp#134]
..when I have defined this TEST_RUNNER:
!define TEST_RUNNER {..\Output\x64\release\Runner.exe}

If I replace with capital R in release it works!

!define TEST_RUNNER {..\Output\x64\Release\Runner.exe}

or even better, use forward slash:

!define TEST_RUNNER {../Output/x64/release/Runner.exe}

**Comment by jediwhale** [comment]
It's a FitNesse issue: https://github.com/unclebob/fitnesse/issues/823
