### ISSUE TITLE
DbFit QueryStored test fails

### ISSUE THREAD

**Issue by reprive** [jediwhale/fitsharp#136]
When running the QueryStored test from the FitSharp DBFit test suite, I run into the following issue:
![querystored](https://cloud.githubusercontent.com/assets/5294830/8784033/004347d0-2f20-11e5-8e0a-158b83eb9eed.png)
It seems that the query fixture doesn't work with stored queries. Any ideas what's wrong? All other fuctionality that I tried works fine.

I'm running FitSharp 2.3 on FitNesse 20150424

**Comment by reprive** [comment]
I retried with FitSharp 2.2, and there it works fine. So this seems to be an issue introduced in FitSharp 2.3.

**Comment by jediwhale** [comment]
fixed - bug introduced in 2.3
