### ISSUE TITLE
Timeout while reading slim header when running a test

### ISSUE THREAD

**Issue by jllanten** [jediwhale/fitsharp#140]
@jediwhale: sorry to add you like this, i couldn't find another way (including PM) to get your attention:

We're having errors when trying to run a fixture: It runs ok the first 5 times (using runner.exe) and it's fast (1 second). But on the 6th call it fails with this error:

Could not complete testing: fitnesse.slim.SlimError: Timeout while reading slim header from client

The odd thing is that after this error we could again run the test correctly for 9 calls and fails on the 10th with the same error. And this pattern continues.

We're using The latest fitnesse version (no plugins) and release 2.3.net.40 and 're using port 9456 (random). 

An additional weird situation happens if we change the port: when using the port 8088 it fails the first tie on the 4th call (the first time) and the on the second call it fil with the same error BUT the console contains this error too:

Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]

After it it fails every 7th call and the every 2nd call.

**Comment by jllanten** [comment]
Notice that i tested with an old fitnesse version (but same fitSharp one): v20131110 on port 8088 and it failed on the 3rd call and with an even weirder behavior: fitnesse never recovered itself after a failed test in some cases (needed to stop it manually) and then could test again for 5/6 times and then again the fail/not recover/stop pattern. THe console had this error:

Error reading Slim Version. Read the following: HTTP/1.1 408 Request Time-out
fitnesse.slim.SlimError: Slim Protocol Version Error: Server did not respond with a valid version number

**Comment by reprive** [comment]
I have the same issue, running FitNesse 20151230 with FitSharp 2.4. It follows the same pattern as described above. The test runs fine 5 times, then I get an error the 6th time. Then it runs fine 9 times and an error occurs the 10th time. From that moment on, every 10th time fails. It seems to just wait there till the timeout kicks in, and then the following message appears: "Could not complete testing: fitnesse.slim.SlimError: Timeout while reading slim header from client. Check that you are connecting to the right port and that the slim client is running. You can increase the timeout limit by setting 'slim.timeout' in the fitnesse properties file."

![could not complete testing](https://cloud.githubusercontent.com/assets/5294830/12941544/df272152-cfd3-11e5-9518-c530ef28f41f.JPG)

This happens with whatever test I take - from the simplest test that just checks a C# Fibonacci function to a test that verifies proper operation of an Excel sheet.
 
slim.timeout is on 30 seconds.

The execution log shows:

System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at fitSharp.Slim.Service.Messenger.Make(Int32 port)
   at fitSharp.Slim.Service.Runner.ParseCommandLine(IList`1 commandLineArguments)
   at fitSharp.Slim.Service.Runner.Run(IList`1 commandLineArguments, Memory memory, ProgressReporter reporter)
   at fitSharp.Machine.Application.Shell.Run()
   at fitSharp.Machine.Application.Shell.Execute()
   at fitSharp.Machine.Application.Shell.Run(IList`1 commandLineArguments)

**Comment by jediwhale** [comment]
Finally managed to reproduce this!

Slim cycles through a set of ports, defined by slim.port and slim.pool.size. These defaults are 8085 and 10, so if you're using port 8090, e.g., for something else, you get the behavior you describe.  The solution is the change the defaults so you don't get conflicting use of ports.

See http://www.fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.SliM
