### ISSUE TITLE
Is it possible to mix java (jar) libraries with C# dll 's?

### ISSUE THREAD

**Issue by sbellus** [jediwhale/fitsharp#141]
Hi

We are using C# fixtures to test our system.

Now it is time to start test of our web frontend. I found the xebium plugin for Fitnesse is handy for us.
The problem is that I am not able to mix C# and Java libraries in fitsharp runner.

Do you see some way how to use java libraries also in fitsharp?

If the question sound funny, perhaps it is because I'm C++ developer :).

**Comment by jediwhale** [comment]
No, it is not possible to run Java fixtures with fitSharp.  You have to set up a separate environment to run the Java tests.
