### ISSUE TITLE
MemberMissingException on second call

### ISSUE THREAD

**Issue by Thaoden** [jediwhale/fitsharp#142]
When using a SUT in a `DoFixture` to explore its behaviour, the first call to a fixture-method succeeds but fails after invoking a SUT-method:
![untitled](https://cloud.githubusercontent.com/assets/3832723/11974937/20132bc0-a969-11e5-8386-c8e6fe1bce7a.png)

    public class ConfigurationCharacterization : fitlibrary.DoFixture
    {
        ConfigurationDelegator cd = new ConfigurationDelegator();
        public ConfigurationCharacterization()
        {
            mySystemUnderTest = cd;
        }

        public int AmountOfConfigsLoaded()
        {
            return cd.GetAllConfigs().Count;
        }
    }

    //delegates calls to the static methods of Configuration
    public class ConfigurationDelegator : Configuration
    {
        public new void Clear()
        {
            Configuration.Clear();
        }

        public new Configuration GetSingletonByIdentifier(string ident)
        {
            return Configuration.GetSingletonByIdentifier(ident);
        }

        public new List<Configuration> GetAllConfigs()
        {
            return Configuration.GetAllConfigs();
        }
    }

`Runner.exe`, `fit.dll` and the fixture dll are all located in the same folder. Where does the `MemberMissingException` come from?

**Comment by jediwhale** [comment]
This is because 'GetSingletonByIdentifier' returns an object: a 'Configuration' object.  This object is then wrapped in a new DoFixture and processes the rest of the table. So the second 'check' is looking for 'AmountOfConfigsLoaded' on the 'Configuration' object.   See the last example in http://fitsharp.github.io/Fit/FixtureWrapper.html
