### ISSUE TITLE
Suite configuration file requires empty path specification

### ISSUE THREAD

**Issue by reprive** [jediwhale/fitsharp#144]
I'm using a suite configuration file to specify fixture assemblies, and I expected that with that, `!path` statements are no longer needed. 

This is the plumbing I use:
`!define COMMAND_PATTERN {%m -c ExcelFixture\config.xml -r fitsharp.Slim.Service.Runner,${FitSharp}\fitsharp.dll %p}`

Here is the config file:
```
<?xml version="1.0" encoding="utf-8" ?>
<suiteConfig>
    <ApplicationUnderTest>
        <AddAssembly>ExcelFixture\ExcelFixture.dll</AddAssembly>
        <AddNamespace>ExcelFixture</AddNamespace>
    </ApplicationUnderTest>
</suiteConfig>
```
However when I run the test, all tests show `Test not run`.
![test not run](https://cloud.githubusercontent.com/assets/5294830/13950891/e648781c-f02d-11e5-8aa5-74636b251815.JPG)

After quite some trial and error, I found out that I needed to add `!path "" ` to make the test work:
![test run](https://cloud.githubusercontent.com/assets/5294830/13950907/f812c5a2-f02d-11e5-9e40-0a63f82f11e3.JPG)

Would it be possible to fix this so path statements are no longer required when suite configuration files are used?

I'm using FitNesse 20151230 and FitSharp 2.4.

**Comment by jediwhale** [comment]
This message is coming from the Fitnesse Slim code, not the FitSharp code, so there's nothing I can do about it.  Please post this issue on unclebob/fitnesse so one of the Slim maintainers can look at it.
