### ISSUE TITLE
Could not complete testing: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT

### ISSUE THREAD

**Issue by rsvijaymca** [jediwhale/fitsharp#146]
Could not complete testing: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT

I am able to do browser testing using JAVA, the same i tried with .Net C# with fitsharp.dll (release.2.5.1.net.4.0) the browser is opening properly but the result is not reflecting in fitnesse page.

I am using below .NET versions
Microsoft Visual Studio Professional 2015
Microsoft .NET Framework Version 4.6.01586

Please advice
Vijay (9600010921)

**Comment by jediwhale** [comment]
There seems to be a problem in the latest Fitnesse version with using 
default Slim port, fitSharp and Selenium together.  I haven't been able 
to recreate it. But as a workaround you can include the line !define 
slim.port {8085} (or any other free port).

**Comment by rsvijaymca** [comment]
Thank you Mike, it worked!

**Comment by rsvijaymca** [comment]
Hi Mike,

Is it possible to hide/controle the style of the below from FitNesse page???
1. Test Summaries
slim:C:\Copy\packages\FitSharp.2.5.0\lib\net40\Runner.exe
2. Test System: 
slim:C:\Copy\packages\FitSharp.2.5.0\lib\net40\Runner.exe

**Comment by jediwhale** [comment]
I don't know how to do it.  You could ask the question on the fitnesse 
yahoo group - there are many knowledgeable people who might be able to help.
