### ISSUE TITLE
Using .Net Standard DLLs as fixtures

### ISSUE THREAD

**Issue by essenius** [jediwhale/fitsharp#150]
I tried to create a fixture using .Net Standard 2.0, but that didn't work - I get "test not run". If I recreate the fixture in .Net 4.6 it works fine. 

Are there any plans of supporting .Net Standard in FitSharp?

**Comment by jediwhale** [comment]
I'll look into it

**Comment by jediwhale** [comment]
fitSharp will have to be upgraded to .NET 4.6.1 to make this work out of the box.  In the meantime, this workaround seems to work:  copy netstandard.dll from c:\program files\dotnet\shared\microsoft.netcore.app\2.0.x to the folder with the fitSharp binaries.

**Comment by jediwhale** [comment]
.net core 2.0 now supported

**Comment by kayjtea** [comment]
Where is the dotnet core runner?
