### ISSUE TITLE
.NET Core runner

### ISSUE THREAD

**Issue by kayjtea** [jediwhale/fitsharp#154]
Repo is only building the .net framework runner.exe. Can someone point me to the .NET Core 2.0 runner?

Thanks!

**Comment by kayjtea** [comment]
Found it; needed to build it as it's not in the release yet. Thanks.

**Comment by kayjtea** [comment]
I could look into migrating source to .net core and support multi-target builds. Is this something that would be accepted as a pull request?

**Comment by jediwhale** [comment]
build.cmd builds for .net framework, buildcore.cmd builds for .net core.  Nuget version 2.7 contains the .net core assemblies.
