### ISSUE TITLE
dotnetcore - FitClient communication socket was not received on time

### ISSUE THREAD

**Issue by OldSmalltalker** [jediwhale/fitsharp#158]
Can not get Fitnesse to work at all with .net core fixtures.

I constantly get: "FitClient communication socket was not received on time"
I have tried 2 different machines.

I am using latest Fitnesse 20190421 and latest 2.7 FitSharp.

pinpointed issue here:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/49890332/56547696-cabb5680-6543-11e9-8b43-003d7cf23c39.png">

It just hangs.  I have turned off Windows Firewall on each machine... no workie.  Here are my Fitnesse settings:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/49890332/56548027-985e2900-6544-11e9-944a-a537a2355859.png">

What am I missing?

**Comment by jediwhale** [comment]
Do you have the correct Runner in the suite config file?

> The Suite Configuration File contains information required to run our tests:
> The Runner tag indicates the class that runs the tests: fitnesse.fitserver.FitServer for Fit tests or fitSharp.Slim.Service.Runner for Slim tests.

**Comment by OldSmalltalker** [comment]
> Do you have the correct Runner in the suite config file?
> 
> > The Suite Configuration File contains information required to run our tests:
> > The Runner tag indicates the class that runs the tests: fitnesse.fitserver.FitServer for Fit tests or fitSharp.Slim.Service.Runner for Slim tests.

Yes that was it.  That makes sense.  Was not 100% clear in documentation.  Thank you!
