### ISSUE TITLE
x64-bit version build target and nuget package.

### ISSUE THREAD

**Issue by briandesarmo** [jediwhale/fitsharp#161]
We just moved from an old version of FitNesse.DotNet to fitsharp and are unable to get it to work with our project which has all x64-bit dlls as is. We were using  CorFlags.exe with FitNesse.DotNet, but this no longer is working. We are able to use fitsharp by creating a x64-bit build target and building from source, but would prefer an official 64-bit nuget package. Would it be possible to release a 64-bit nuget package?

Thanks
@briandesarmo

**Comment by jediwhale** [comment]
What problem did you have with corflags? It works OK for me.
copy runner.exe to runner64.exe
corflags /32BIT- runner64.exe
