### ISSUE TITLE
SDK Style Projects and multitarget net472 and netcoreapp3.1

### ISSUE THREAD

**Issue by sqeezy** [jediwhale/fitsharp#166]
I am looking to use fitsharp with classic framework aswell as netcoreapp. Would you accept a PR with that work being done and do you think there is a technical blocker for that?

**Comment by jediwhale** [comment]
Should be no problems to target for net472 and netcore31. Happy to get a PR.

**Comment by sqeezy** [comment]
What is the status on this issue. Can I help somehow?

**Comment by jediwhale** [comment]
done
