### ISSUE TITLE
FitSharp is not getting built/compiled with .Net SDK netstandard2.0

### ISSUE THREAD

**Issue by pb1981** [jediwhale/fitsharp#170]
It seems netstandard2.0 or 2.1 does not support System.AppDomainSetup  class but FitSharp code uses AppDomainSetup class in Application Shell. 
Did anyone face this issue or Is there any work-around any body tried or aware?
Is there a plan for fitsharp to support .Net SDK?

**Comment by jediwhale** [comment]
fitSharp is now built for .net 4.6.2 and .net core 3.1.  The project files are now in the .net sdk format.
