### ISSUE TITLE
Abandon Story on first exception

### ISSUE THREAD

**Issue by LodewijkSioen** [jediwhale/fitsharp#171]
We're using FitSharp to automate Selenium scenario's. The problem is that when one step fails, Fit will continue with the following steps. This will cause Selenium to search for elements on a page that is in an invalid state in the next steps. Selenium will timeout when the element is not found, but this causes the tests to run extremely slow when something is wrong.

I see that there is an [AbandonStoryTestException](https://fitsharp.github.io/Fit/AbandonStoryTest.html), but I have no hook to throw this exception.

What I would like is to abandon the story test on the first exception thrown. Is this possible?

**Comment by jediwhale** [comment]
Can you write wrapper functions to throw AbandonStoryTestException? e.g.
`public void Something(some parameters...) {
    try {
        Selenium.Something(some parameters);
    }
    catch (Exception e) {
        throw new AbandonStoryTestException(e.Message());
    }
}`

**Comment by LodewijkSioen** [comment]
That would mean hundreds of wrapper functions. All my fixtures inherit DoFixture, so I was able to do the following:
```
public override void DoTable(Parse table)
 {
    base.DoTable(table);

    if (TestStatus.Counts.GetCount("error") > 0)
    {
        TestBrowser.CloseBrowser();
        throw new AbandonStoryTestException("An error occured during this StoryTest. Abandoning test to avoid stale state.");
    }
}
```

Seems a bit hackish, but it does the job as long as there are not too many rows in a table. Is there a better function that I can override this way?

**Comment by jediwhale** [comment]
Looks like a good solution
