### ISSUE TITLE
How to start dbfit .net server

### ISSUE THREAD

**Issue by Luisss** [jediwhale/fitsharp#173]
Hi, 
I have been using the java version of dbfit for a while, but now i have to use the .net version because of sybase support.
I can't find documentation on how to start the dbfit .net server.

Any help will be appreciated.
Thanks.

**Comment by jediwhale** [comment]
DBFit .NET tests are run the same as other Fit tests, see: https://fitsharp.github.io/FitSharp/RunTestsWithFitnesse.html
You need to add the DBFit libraries to your configuration. see https://fitsharp.github.io/DbFit.html
Note: no-one has maintained DBFit .NET for several years so I don't know if it works with current database versions.

**Comment by Auguronomics** [comment]
Just define at the root level of your project folder on the wiki server side :
path : ./dbfit/FitNesseRoot/MySqlProject/content.txt 


`!***< default configuration
!define COMMAND_PATTERN {%m -r fitnesse.fitserver.FitServer %p}
!define TEST_RUNNER {fitsharp\Runner.exe}
!define PATH_SEPARATOR {;}
!path fitsharp\*.dll
*!`
