### ISSUE TITLE
.NET 5 Support ( platform specific? )

### ISSUE THREAD

**Issue by sqeezy** [jediwhale/fitsharp#174]
As Dotnet Core 3.1 is supported, .NET 5 should not be too far of. My company actually would need compatibility with "net5.0-windows".
I'd like to open a discussion about the topic and offer help if needed.

**Comment by jediwhale** [comment]
added .net 5 support, pushed fitSharp 2.8.2 to nuget

**Comment by sqeezy** [comment]
Thanks for the fast turnaround.
As the dlls/exes we want to test have to be net5.0-windows, can we also include that target?
