### ISSUE TITLE
Need very old versions of Fit and FitLibrary for work on legacy project.

### ISSUE THREAD

**Issue by awa5114** [jediwhale/fitsharp#186]
I'm working on a legacy project which makes use of two DLLs:

- `fit.dll`
- `FitLibrary.dll`

The usages of `fit.dll` in the source code include the following:
- `FileRunner`
- `Fixture`

The usages of `FitLibrary.dll` in the source code include the following:
- `fitlibrary.exception.FitFailureException`

I did some digging and checked some of the earliest tagged versions of `fitsharp` on this repository, but I could find no source files called `FileRunner`. So I digged deeper and discovered the 1.x versions of Fit on [sourceforge](https://sourceforge.net/projects/fit/files/fit-dotnet/) which do contain a source file named `FileRunner`. 

I'm assuming the legacy project is making use of one of these 1.x versions, however when I unzipped the downloads from source forge I could find no files with the name `FitLibrary`. I checked again on source forge and found only [this](https://sourceforge.net/projects/fitlibrary/) which doesn't seem to have any .NET binaries or source.

Where can I find the version of FitLibrary corresponding to the 1.x versions of Fit?

Thanks

**Comment by jediwhale** [comment]
Here's some old stuff https://sourceforge.net/projects/fit/files/fit-dotnet/

**Comment by jediwhale** [comment]
Some old stuff I found
[fitLibrary.zip](https://github.com/jediwhale/fitsharp/files/11183558/fitLibrary.zip)

**Comment by jediwhale** [comment]
You can probably just strip out all the logic from FitVersionFixture since your legacy project likely isn't using it. e.g.
`public static bool IsStandard {get { return true;}}`
