### ISSUE TITLE
Nuget Release for Dotnet 8 Version

### ISSUE THREAD

**Issue by sqeezy** [jediwhale/fitsharp#192]
We should release the current state to nuget so people don't have to roll their own nuget package.

**Comment by mikestockdale** [comment]
I no longer work with Windows and .NET so I don't have an up-to-date development environment. If you're willing, I can add you as an owner of FitSharp on nuget so you can update it.

**Comment by afmg-aherzog** [comment]
I would be happy to do that.
If it's fine with you, I'd just create an automatic workflow for releasing new versions of fitsharp. Otherwise I just do it manually. 
My nuget username is `sqeezy` as well.

**Comment by sqeezy** [comment]
I would be happy to do that.
If it's fine with you, I'd just create an automatic workflow for releasing new versions of fitsharp. Otherwise I just do it manually. 
My nuget username is `sqeezy` as well.

**Comment by sqeezy** [comment]
Release 2024.02.27 published.
