### ISSUE TITLE
Cleanup not needed projects

### ISSUE THREAD

**Issue by sqeezy** [jediwhale/fitsharp#195]
While working on .NET 9 support in #194 I got wondering whether we need all the projects/functionality as it is now.
I know that going forward I will have to do maintenance for most things in this repo and I'm not actually able to ensure the database libraries are working correctly. Do we have any idea on the amount of people using these features? A some point I'd like to cleanup the core of the codebase and bring it up to current dotnet coding standards and features. This is covered from the company I work on as well.

My proposal would be discussing the removal of...
- dbfit
- dbfitOracle
- dbfitMySql
- dbfitSqlServer
- dbfitSybase
- dbfitTest

Alternatively we could keep the parts that are integration tested easily, but that would have to be documented and cleaned up then.

What are your thoughts @jediwhale?

There is no hurry in any of this as the .NET 9 support is basically finished. So the next time this get's urgent could be .NET 10.

**Comment by mikestockdale** [comment]
I agree to remove the dbfit code. It was donated to the fitSharp project many years ago and has not been maintained for a long time.
